# 1. Finding Clearing liability Payment Vector


In [54]:
import numpy as np

let us consider four banks,which are interconnected to each other at T=0 through liabilities, then at time T=1 banks has to clear their obligation which they owes to each other.
Let Liability Matrix of banks is given by :

In [55]:
liability_matrix= [[0,7,1,1],[3,0,3,3],[1,1,0,1],[1,1,1,0]]
print("liabiity matrix of banks is :", liability_matrix)

liabiity matrix of banks is : [[0, 7, 1, 1], [3, 0, 3, 3], [1, 1, 0, 1], [1, 1, 1, 0]]


Then fractional liability matrix is given by :

In [61]:
fractional_liability_matrix_sum= np.sum(liability_matrix, axis=1, keepdims=True)
fractional_liability_matrix = liability_matrix / fractional_liability_matrix_sum
print("Fractional liabilities of banks is given by: \n",fractional_liability_matrix)


Fractional liabilities of banks is given by: 
 [[0.         0.77777778 0.11111111 0.11111111]
 [0.33333333 0.         0.33333333 0.33333333]
 [0.33333333 0.33333333 0.         0.33333333]
 [0.33333333 0.33333333 0.33333333 0.        ]]


In [57]:
initial_p1 = 9
initial_p2 = 9
initial_p3 = 3
initial_p4 = 3
clearing_payment_vector = [initial_p1 ,initial_p2 , initial_p3, initial_p4]

#Running iteration for 100 times and then calculating payment liabilty vector for each banks. 

In [58]:
for j in range(100):
    CLEARING_VECTOR=[]
    for i in range(4):
        clearing_payment =(min(np.sum(fractional_liability_matrix[:,i]*clearing_payment_vector),fractional_liability_matrix_sum[i]))
        if clearing_payment == clearing_payment_vector[i]:
            clearing_payment_vector[i] = clearing_payment_vector[i]
            CLEARING_VECTOR.append(clearing_payment_vector[i])
        else :
            clearing_payment_vector[i] = clearing_payment
            CLEARING_VECTOR.append(clearing_payment)
print("CLEARING PAYMENT VECTOR OF BANK 1, 2, 3 and 4 is ",CLEARING_VECTOR,"respectively")


CLEARING PAYMENT VECTOR OF BANK 1, 2, 3 and 4 is  [3.6, 4.800000000000001, array([3]), array([3])] respectively


# Clearing liability payment which is obtain above is unique.

### but this clearing liability payment vector depends upon initial or starting value.

# 2. Finding Clearing Price of Illiquid Assets.

Justification whether the calculated Clearing payment vector is correct or not.

In [50]:
for i in range(4):
    clear_balance_bank=[]
    for i in range(4):
        clear_balance = fractional_liability_matrix[i]* CLEARING_VECTOR[i]
        clear_balance= np.sum(clear_balance, axis = 0, keepdims = True)
        clear_balance_bank.append(clear_balance)
for i in range(4):
    print("Clearing Balance of bank ",[i+1], ":",clear_balance_bank[i])
    
    

Clearing Balance of bank  [1] : [3.6]
Clearing Balance of bank  [2] : [4.8]
Clearing Balance of bank  [3] : [3.]
Clearing Balance of bank  [4] : [3.]


total liability of bank 1 is  9 , 
total liability of bank 2 is  9 ,
total liability of bank 3 is  3 , 
total liability of bank 4 is  3 ,

Equity is thus calculated by Assets - Liabilities, thus net balance of each bank is :


In [51]:
net_balance_bank=[]
for i in range(4):
    net_balance = clear_balance_bank[i] - fractional_liability_matrix_sum[i]
    net_balance_bank.append(net_balance)
print("Equity of bank",":",net_balance_bank)

Equity of bank : [array([-5.4]), array([-4.2]), array([0.]), array([0.])]


* negative sign denotes bank suffer from shortfall (i.e they are not able to pay its liabilities) thus to avoid default bank will undergoes force liquation of illiquid assets at distressed price.If liquation of illiquid assets willnot take pace then maturity amount from illiquid assets at T =1 is P. Let us assume P =20

In [52]:
illiquid_assets=[0,2,2,2]
maturity = P = 20
Clearing_price=[]
for i in range(4):
    if (net_balance_bank[i] < 0 and illiquid_assets[i] > 0):
        price_assets = - net_balance_bank[i]/illiquid_assets[i]
        Clearing_price.append(price_assets)
    elif (net_balance_bank[i] < 0 and illiquid_assets[i] == 0):
        Clearing_price.append(0)
    else:
        Clearing_price.append(maturity)
print("CLearing price of illiquid assets is :", Clearing_price)

CLearing price of illiquid assets is : [0, array([2.1]), 20, 20]


* from above it is clear that if the price of illiquid assets at time of pre-mature liquidation is 2.1 then by selling all the 2 units , Bank 2 will recover from default.


# 3. Apply Full Netting in order to reduce Systemic Risk.

By applying netting, net clearance amount is to be paid to central counter party (CCP) thus it can reduces systemic risk.
Net clearance amount which is to be paid is given by Net_money_to_CCP

In [59]:
fractional_liability_matrix_sum
money_from_other_banks = np.sum(liability_matrix,  axis =0 , keepdims =True)
net_money_to_CCP=[]
for i in range(4):
    net_money_CCP = fractional_liability_matrix_sum[i] - money_from_other_banks[0][i]
    net_money_to_CCP.append(net_money_CCP)
print("Net Clearance amount to be paid by bank to CCP is given by :",net_money_to_CCP)

Net Clearance amount to be paid by bank to CCP is given by : [array([4]), array([0]), array([-2]), array([-2])]


By appling 